// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "graphqlEndpoint": "https://jdvwdbfcgvaybli2egkywrjurm.appsync-api.us-east-1.amazonaws.com/graphql",
    "region": "us-east-1",
    "authenticationType": "API_KEY",
    "apiKey": "da2-yoqp7sxygnfpdkrbp7rlunpb5i",
};

export default awsmobile;